### ISSUE TITLE
Tracking is not working

### ISSUE THREAD

**Issue by Orshabal** [colinlaney/animal-tracking#11]
Hello,

I'm running the code but the tracking is not working even with the video attached to the zip file.
It seems to follow the bright spots but rarely the rat as you can see in the video.

https://user-images.githubusercontent.com/20100100/121676121-a657c680-ca8a-11eb-8239-78c97a7107bb.mp4

I've tried to play with the threshold but without success. Any suggestions?

Thank you a lot for your effort!

**Comment by eggplants** [comment]
Same

**Comment by LucasBei** [comment]
Try to fix the threshold in column 11 and 12:
THRESHOLD_WALL_VS_FLOOR = 80
THRESHOLD_ANIMAL_VS_FLOOR = 110
(This makes better results for me)

**Comment by colinlaney** [comment]
@LucasBei, actually `threshold` has to be adaptive. But since it is not at the moment, everyone fix the threshold regarding her lighting, like you.
