### ISSUE TITLE
Taking the right side square of the camera environment

### ISSUE THREAD

**Issue by Hatem-Jr** [colinlaney/animal-tracking#12]
Hi I am trying to change the behavior of the code where it does not take the right side square of the video (frame[:, w-h:w]) or the left side for that matter and I want it to take the full video without any section of pixels cut off so that I can crop the full test environment (in my case it's a Morris Water Maze test if you're wondering).

**Comment by colinlaney** [comment]
Well, [commenting](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L91) `frame = frame[:, w-h : w]` should work fine.

**Comment by Hatem-Jr** [comment]
you mean all 3 of them or just the one in line 91 ? because when running after selecting the cropping area the frame is still cut in the running state like this:
![Screenshot (4)](https://user-images.githubusercontent.com/47870128/122116842-65fb9e00-ce26-11eb-9ea9-d0863d16b334.png)

**Comment by colinlaney** [comment]
> you mean all 3 of them?

Yes, [91](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L91), [172](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L172), [188](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L188), and [192](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L192).

And don't forget to disable all [cv2.warpPerspective](cv2.warpPerspective) on [131](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L131) and [198](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L198).

**Comment by Hatem-Jr** [comment]
I commented 91 and 191 and left 171 uncommented and the tracing works just fine but thanks for your trouble :D
