### ISSUE TITLE
The cropping method 

### ISSUE THREAD

**Issue by Hatem-Jr** [colinlaney/animal-tracking#13]
Hi it's me again :D, I wanted to know how you did the cropping method (as in moving the mouse and clicking 4 times to crop a dynamic 4 sided shape):
1-I want to know how it is done and if there's any resources that could help me in that
2-If I can  crop more than one ROI (region of field) and have multiple viewable traces for the same video
3-And I know this is a little off topic from what this repo does is to count how many times the mouse entered each ROI and the amount of time spent in it each time it did (I'm doing the Y-Maze Test next to give you some clarification)

Thanks in advance :)

**Comment by colinlaney** [comment]
1. [cv2.warpPerspective](https://github.com/colinlaney/animal-tracking/issues/12#issuecomment-861813093) is a workhorse of [that](https://learnopencv.com/feature-based-image-alignment-using-opencv-c-python/) you call "cropping". This is kind of image alignment, more than just image cropping.
2. You can, but you have to add another viewport for that and stack it alongside of the first one. Definitely, it requires some logic modification.
3. Sure, it is possible.

Don't hesitate to produce feature requests explicitly (in _separate_ issues).

**Comment by Hatem-Jr** [comment]
so.......how can I do 1&2 😂 ? because I tried in the last week and I busted the code up, do you have discord ?

**Comment by colinlaney** [comment]
1. I thought, I have answered. What was the question?
2. Assume the ROIs do not overlap with each other. The simplest way to track different ROIs is to split input video by halves with each ROI and process them as separated videos. Other ways are not so simple and really requires working with cv2.warpPerspetive instances of tetragonal ROIs but I can't guide you step by step.
