### ISSUE TITLE
How is the distance calculated ?

### ISSUE THREAD

**Issue by Hatem-Jr** [colinlaney/animal-tracking#18]
Hi, I wanted to ask how the distance covered is calculated because I want to make the results as accurate to the actual results (specially since I know the size of my test environment) as possible since I'm using this program in my thesis.

Thanks :)

**Comment by colinlaney** [comment]
Assuming the maze is square (or the aspect ratio of the frame is `1:1`), the [distance](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L217) is measured in units of the height of the frame that shows and fits the maze.

Thus the distance is normalized by the height of the frame. I mean if your frame is `400x400` and these 400 pixels are equal to 1 meter then the horizontal displacement of the object from pixel 1 to pixel 40 is 10% off 1 meter, i.e. `40 pixels = 10 cm` when `height = 400 pixels = 1 meter`.

**Comment by colinlaney** [comment]
@Hatem-Jr, please cite the repository with
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5130648.svg)](https://doi.org/10.5281/zenodo.5130648)
in your works.

**Comment by Hatem-Jr** [comment]
> @Hatem-Jr, please cite the repository with
> [![DOI](https://camo.githubusercontent.com/e5a2c4c4f1d5270c55032017f4ce4d201a4a91cd5a5bee70824c8231aa2217c1/68747470733a2f2f7a656e6f646f2e6f72672f62616467652f444f492f31302e353238312f7a656e6f646f2e353133303634382e737667)](https://doi.org/10.5281/zenodo.5130648)
> in your works.

Of course 😄 👍
