### ISSUE TITLE
Can I change the way the distance is calculated ?

### ISSUE THREAD

**Issue by Hatem-Jr** [colinlaney/animal-tracking#19]
Hi, regarding the last issue (which was really helpful in understanding the code), I wanted to ask if there's a way I can change that, meaning to have a pop up appear and ask the user for the dimensions of the area of the video that they selected in order to make the results as accurate as possible ?

Thanks :D

**Comment by colinlaney** [comment]
[floorCrop](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L80) was intended not so much for cropping as for you're asking about: for measuring the distance accurately. The only goal to draw a tetragon on the 1st raw frame is to make processed frames more consistent to reference objects on the scene, say with a known side length of the box or with the known diameter of the circle maze. Then the side length of the tetragon (required being square) will be your unit of measurement. That's why [making the frames rectangular again](https://github.com/Hatem-Jr/animal-tracking/commit/280897e7b4599fe033374fd35b79a6f8762cc6b5#diff-cba6d1cf80376c12d24a63a2bd0e1276a76030f5e9a1da760277c1d0505dc029R92) was the wrong way.

Thus, in the beginning, according to my design, in GUI you mere fit your unit of measurement to the size of your maze. Why don't to post-process resulting distance with normalizing factor instead of interrupting the processing stage by annoying dialogue?

**Comment by Hatem-Jr** [comment]
You mean to just multiply the resulting "distance" by some kind of factor relevant to the size of the actual maze to get the more accurate and actual result after the processing is done ?

**Comment by colinlaney** [comment]
Right.

But if the aspect ratio of the _maze_ differs from 1 (the width of the quad fitting on the maze is not equal to the height), then you have to

1.  normalize both dimensions separately and replace one of two denominators in

`distance += np.sqrt(((x - _x) / float(h))**2 + ((y - _y) / float(h))**2)`

by `w`:

`distance += np.sqrt(((x - _x) / float(w))**2 + ((y - _y) / float(h))**2)`

2. scale the distance to the size of the known dimension of the maze.
 
Examples.
1. If the height of the maze in your lab is 1 meter, then `distance = 5` is the same as `distance = 5 meters`.
2. If the height of the maze is 2 meters, then `distance = 5` is the same as `distance = 2 * 5 meters`.
3. If the _width_ of the maze is 2 meters and the aspect ratio is 4:3 (`maze width / maze height = 1.33`), then `distance = 5` is the same as `distance = 1.33 * 2 * 5 meters`.

Look at these frames

[![ROI](https://raw.githubusercontent.com/colinlaney/animal-tracking/9f9fa589e03c49be0f82159844ec6b6a9723c713/screenshots/good_fit.png)](https://github.com/colinlaney/animal-tracking/tree/9f9fa589e03c49be0f82159844ec6b6a9723c713#user-interface)

Guess [why](https://docs.opencv.org/4.5.2/d9/dab/tutorial_homography.html) am I drawing the quad? Exactly. Accuracy)

I do [perspective correction](https://github.com/colinlaney/animal-tracking/issues/13#issuecomment-865085084) to work with floor plane as a _plane_.

**Comment by Hatem-Jr** [comment]
so I found a way in order to make the view of the test better for the analysis and also a conversion that makes the video has an aspect ratio of 1: 

original:
![Screenshot (16)](https://user-images.githubusercontent.com/47870128/126895433-922027fb-1f4d-4906-9aaa-73cde42acac3.png)

transformed:
![Screenshot (17)](https://user-images.githubusercontent.com/47870128/126895442-9e301310-fe2b-462d-b810-7c6195c86124.png)

and considering that this is a circle that has a diameter then to get a more accurate distance would be:
if for ex: distance = 5
then: distance = distance (5 in this case)  * (2 * 3.14(pie) * (diameter/2)) [circumference] ?
or would distance  = distance *diameter ?

side issue: the detector keeps mistaking the white light reflection on the water to be the mouse, how can this issue be solved ?

**Comment by colinlaney** [comment]
No, you don't need circumference at all ever, forget π. Your solution looks like you had a square maze and you were trying to calculate the distance using the square's perimeter. Then what will you do if the maze is star-shaped? T-shaped?

The shape does not matter. All you need is any linear size of the shape that you fitted to the full frame. Take the diameter, _this_ is your scale factor. Simply `actual distance = distance * diameter`.

**Comment by Hatem-Jr** [comment]
Well thanks man because I was also skeptic at first 😂 and the GUI works fine rn, I'll just make it look better. Seriously, the most helpful repo out of all that I found on this very topic 👍

**Comment by colinlaney** [comment]
Regarding flare effects. Henceforth use [polarizing filters](https://en.wikipedia.org/wiki/Polarizing_filter_(photography)) on your camera.

**Comment by Hatem-Jr** [comment]
oh I forgot I asked that, do I modify this in track.py or in an outer script like the perspective transform ?

**Comment by Hatem-Jr** [comment]
Sorry about the above question it's stupid 😂 I realized that, so I just film with a polarizing filter while recording the test ? sounds easy

**Comment by colinlaney** [comment]
Right, it's easier than do hard postprocessing or use GPU to run neural network object tacking which is smarter than an old-school solution like mine. I believe you don't need to solve the problem programmatically when our days technologies can solve it physically. Polarizing filters do the magic!

Nevertheless, nobody stops you if you add the Calman filter to the tracking algorithm.

**Comment by Hatem-Jr** [comment]
well I'll just tell the guys doing these tests to tone down the lighting for it to work  but I'll try the Calman filter nonetheless

**Comment by colinlaney** [comment]
It seems the [transformed image](https://user-images.githubusercontent.com/47870128/126895442-9e301310-fe2b-462d-b810-7c6195c86124.png) you have [posted](https://github.com/colinlaney/animal-tracking/issues/19#issuecomment-886177859) is just stretched vertically. If so, then this is not perspective transform. @Hatem-Jr, could you please share the original video to make me able to remove glares somehow and check perspective also?

**Comment by Hatem-Jr** [comment]
https://drive.google.com/drive/folders/1ePf13lgxG8mcba1EnfhAPtmgdJOhR9Si?usp=sharing @colinlaney

**Comment by Hatem-Jr** [comment]
were you able to remove the glares coming from the water ? If so it would be really helpful

**Comment by colinlaney** [comment]
Just play with [THRESHOLD_ANIMAL_VS_FLOOR](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L11). In your case `threshold = 140` (of 255) is more than sufficient.

And of course, try to make perspective corrections in the right way, like here

https://user-images.githubusercontent.com/1339345/127750835-ee3ecec7-53cc-4314-a943-74cc6bed9749.mp4

Then you will get correct trace and adequate distance values (assuming `diameter = 1 m`), like this

<img width="1659" alt="Screenshot 2021-07-31 at 22 34 42" src="https://user-images.githubusercontent.com/1339345/127750839-57ff862e-d00c-4fa1-8c35-ee19d1b4e23d.png">

Obviously, focal plane of the camera lens has to be parallel to the plane of the maze. Tilt must go.

**Comment by Hatem-Jr** [comment]
it's alright I already changed the threshold long ago but thank you for your help, and don't worry I referenced u in the thesis
