### ISSUE TITLE
Description of my problem about running long play video file

### ISSUE THREAD

**Issue by hyukhoon** [colinlaney/animal-tracking#20]
Q: Specify input data (codec, resolution), processing time and resources, output errors, and whether you have tried to trim a long video.

A: Codec: Timed metadata, H.264, MPEG-4 AAC
    Resolution: 1080 * 1920
    Processing time: 10 minutes
    Output errors:
```
Traceback (most recent call last):
  File "/Users/hyuk-hoon/Desktop/Animal/animal-tracking-master/track.py", line 287, in <module>
    trace(filename)
  File "/Users/hyuk-hoon/Desktop/Animal/animal-tracking-master/track.py", line 236, in trace
    imgContour = cv2.add(imgPoints, imgTrack)
cv2.error: OpenCV(4.7.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/core/src/arithm.cpp:650:
 error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array'
 (where arrays have the same size and the same number of channels), nor 'array op scalar',
 nor 'scalar op array' in function 'arithm_op'
```

**Comment by colinlaney** [comment]
It looks like you have reshaped the frame on [171](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L171), [188](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L188), or [197](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L197) line such that the shapes of inherited frames differ ([imgPoingts](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L222) and [imgTrack](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L178)). But you can't add matrices of different sizes.

It's almost impossible to debug the hidden code. Please make a [fork](https://github.com/colinlaney/animal-tracking/fork) of the repository, [push](https://github.com/git-guides/git-push) your changes, and refer to it here.

Show an example of your frames (unprocessed (original) and processed by `track.py` if any).
