### ISSUE TITLE
Issues with the code

### ISSUE THREAD

**Issue by Cruz1946** [colinlaney/animal-tracking#21]
I there! As i said on youtube, im having some problems with the code. I already replaced avi for mp4 in all the places where it should. But now im not quiet sure where im supose to put the path to my video. Best regards

**Comment by colinlaney** [comment]
After you put `track.py` next to the videos and run the script it will search all `.avi` (`.mp4` in your case) there.

Answering your question: the path to the videos is on [283](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L283) and [285](https://github.com/colinlaney/animal-tracking/blob/9f9fa589e03c49be0f82159844ec6b6a9723c713/track.py#L285) lines.
