### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by ghost** [colinlaney/animal-tracking#4]
import track.py

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "track.py", line 252, in <module>
    floorCrop(filename)
  File "track.py", line 91, in floorCrop
    _, contours, hierarchy = cv2.findContours(mask, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack

I'm testing the module with your rat.avi video. But I get value error. How to fix the error?

**Comment by colinlaney** [comment]
@philosophus23, please pull new version.

And note that `track.py` is standalone "app", not a module. Better use it as `python track.py`.

**Comment by philosophus23** [comment]
@colinlaney Yes, I use the module in Spyder python IDLE
